### ISSUE TITLE
Use Sequelize ORM?

### ISSUE THREAD

**Issue by shreevari** [osl-vvce/quiz-platform-server#5]
Do we want to use Sequelize ORM for this project?
@dantehemerson @sanjithpk @suresh-44

**Comment by sanjithpk** [comment]
I don't think we need that, because with knex.js we can do much more than just ORM.

**Comment by dantehemerson** [comment]
I used a little Sequelize and it seemed like a great tool for simplicity and the schemes. I have not used Knex but it looks very interesting, I think knex could be a great option and we should use it.

**Comment by sanjithpk** [comment]
Okay, its decided the, lets use knex as a query builder.
